name: CMake Build with vcpkg on Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_DIR: ${{ github.workspace }}/build
  ARTIFACT_FILENAME: ziptool.exe
  
jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup anew (or from cache) vcpkg (and does not build any package)
      uses: lukka/run-vcpkg@v11
      
    - name: Configure CMake
      run: >
        cmake -B "${{ env.BUILD_DIR }}"
        -S "${{ github.workspace }}"
        -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake"
        -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build "${{ env.BUILD_DIR }}" --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ziptool-windows-x64
        path: ${{ env.BUILD_DIR }}/**/${{ env.ARTIFACT_FILENAME }}
        if-no-files-found: error
